############# French navigation ##############

# main menu
[[main]]
name = "Manifesto"
url = "/manifesto"
weight = 1

[[main]]
name = "Framework"
url = "/framework"
weight = 2

[[main]]
parent = "Framework"
name = "CAF"
url = "/framework"
weight = 1

[[main]]
parent = "Framework"
name = "Rôles"
url = "/roles"
weight = 2

[[main]]
parent = "Framework"
name = "Rituels"
url = "/rituals"
weight = 3

[[main]]
parent = "Framework"
name = "Pratiques"
url = "/practices"
weight = 4

[[main]]
name = "Glossaire"
url = "/glossary"
weight = 3

[[main]]
name = "À propos"
url = "/authors"
weight = 4

[[main]]
parent = "À propos"
name = "Mainteneurs"
url = "/authors"
weight = 1

[[main]]
parent = "À propos"
name = "Association"
url = "/organization"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 5

# footer menu
[[footer]]
name = "Gouvernance"
url = "/governance"
weight = 1

[[footer]]
name = "Politique de confidentialité"
url = "/privacy-policy"
weight = 2

[[footer]]
name = "Nous soutenir ❤️"
url = "https://opencollective.com/continuous-architecture-toolkit"
weight = 3
